#Information needed before the Installer is loaded.
#Tue May 05 15:46:53 CST 2020
lax.stderr.redirect=D:/InstallAnywhere/IPMIView20/InstallerStdErrRedirect.txt
DefaultLanguage=en
InstallerTitle=IPMIView
ProductName=IPMIView
ia.custom.code.zip.size=0
splashScreenConsoleTitle_en=Choose Locale...
splashScreenGUIImage_en=$IA_PROJECT_DIR$/resources/254563a034ed41e4e80b453700885aba/Splash.png
Locales=en 
splashScreenGUIConfirm_en=OK
splashScreenConsolePrompt_en=CHOOSE LOCALE BY NUMBER
lax.installer.unix.ui.default.purejava=GUI
Designer_Chosen_Default_Locale=English - en
lax.installer.windows.ui.default.purejava=GUI
lax.stdout.redirect=D:/InstallAnywhere/IPMIView20/InstallerStdOutRedirect.txt
splashScreenGUIInstructions_en=
splashScreenGUITitle_en=
