#Information about each Media item..
#Tue Feb 13 16:41:26 CST 2018
.INSTALLED_MEDIAS..BUILD_INFO.isOptimized=false
.INSTALLED_MEDIAS..BUILD_INFO.isWebInstaller=true
.INSTALLED_MEDIAS..BUILD_INFO.Platform=
.INSTALLED_MEDIAS.0.MEDIA_ID.id=a1d47f0e9a7e
.INSTALLED_MEDIAS.0.INSTALLED_MEDIA.Volume=1
.INSTALLED_MEDIAS.Size=1
.INSTALLED_MEDIAS.0.INSTALLED_MEDIA.ZipName=Resource1.zip
.INSTALLED_MEDIAS.0.INSTALLED_MEDIA.MediaName=Disk1
